# Generated by Django 3.2.14 on 2022-08-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='contents',
        ),
    ]
